Don't include built theme files in PRs (#99)

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -1,15 +1,19 @@
-name: Check that building template does not produce additional changes
+name: "Pull Request"
+
 on:
   pull_request:
-    branches:
-      - main
+    paths:
+      - "colors/*.vim"
+
 jobs:
-  check:
+  check-generated-theme-directories:
     runs-on: ubuntu-latest
     steps:
-      - name: Fetch the repository code
+      - name: Checkout repository
         uses: actions/checkout@v4
-      - name: Update schemes
-        uses: tinted-theming/tinted-builder-rust@latest
-      - name: Check if there are changes
-        run: git diff --exit-code
+
+      - name: Check for changes in restricted directories
+        run: |
+          echo "Error: Changes detected in generated theme directory."
+          echo "this directory should be generated by tinted-theming-bot after merge."
+          exit 1
